#!/bin/sh
set -e

oldpwd=$PWD
cd $(dirname $(readlink $0))
. ./functions
cd $oldpwd

checkvar DEVO_NAME
checkvar DEVO_PREFIX
checkvar DEVO_CMAKE_BUILD_TYPE

usage() {
    if [ -n "$1" ] ; then
        echo "ERROR: $*"
        echo
    fi

    cat <<EOF
devo-cmake [<options>] [<sourcedir>]

Options:
    -h, --help        this screen

All other options are directly passed to cmake.

Arguments:
    sourcedir         path to source dir. If no path is provided, devo-cmake
                      will use devo-get-source-dir to find one.
EOF
    exit 1
}

args=""
src_dir=""

for arg in $* ; do
    case $arg in
    -h|--help)
        usage
        ;;
    -*)
        args="$args $arg"
        ;;
    *)
        if [ -z "$src_dir" ] ; then
            src_dir=$arg
        else
            usage "Too many arguments"
        fi
        ;;
    esac
done

if [ -z "$src_dir" ] ; then
    if [ -e "CMakeLists.txt" ] ; then
        # We are in the source dir, go to the buid dir
        src_dir=$PWD
        if ! build_dir=$(devo-get-build-dir) ; then
            exit 1
        fi
        echo "devo-cmake: using '$build_dir' as build dir"
        cd $build_dir
    else
        # Assume we are in a build dir
        src_dir=$(devo-get-source-dir)
        [ -d "$src_dir" ] || die "Could not find a source dir for $PWD"
        echo "devo-cmake: using '$src_dir' as source dir"
    fi
fi

cmake \
    -DCMAKE_INSTALL_PREFIX=$DEVO_PREFIX \
    -DCMAKE_BUILD_TYPE=$DEVO_CMAKE_BUILD_TYPE \
    $src_dir $args
