#!/bin/sh
set -e

oldpwd=$PWD
cd $(dirname $(readlink $0))
. ./functions
cd $oldpwd

checkvar DEVO_NAME
checkvar DEVO_PREFIX
checkvar DEVO_CMAKE_BUILD_TYPE

if [ $# = 0 ] ; then
    [ -n "$DEVO_SOURCE_BASE_DIR" ] || die "No argument given and no \$DEVO_SOURCE_BASE_DIR environment variable set"
    dir=$DEVO_SOURCE_BASE_DIR/$(basename $PWD)
    [ -d "$dir" ] || die "Tried to find source dir from \$DEVO_SOURCE_BASE_DIR, but \"$dir\" does not exist"
fi

cmake \
    -DCMAKE_INSTALL_PREFIX=$DEVO_PREFIX \
    -DCMAKE_BUILD_TYPE=$DEVO_CMAKE_BUILD_TYPE \
    $dir $*
